name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  get-version:
    name: Get version from tag
    runs-on: ubuntu-latest
    steps:
      - name: Get version from tag
        id: version-from-tag
        run: |
          version=$(echo ${{ github.ref_name }} | cut -c 2-)
          echo "version=$version" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.version-from-tag.outputs.version }}
  build-and-stage-release:
    if: ${{ github.repository == 'spring-io/develocity-conventions' }}
    name: Build and stage release
    needs: get-version
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'liberica'
          java-version: 8
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-provider: basic
      - name: Configure Gradle properties
        shell: bash
        run: |
          mkdir -p $HOME/.gradle
          echo 'systemProp.org.gradle.internal.launcher.welcomeMessageEnabled=false' >> $HOME/.gradle/gradle.properties
          echo 'org.gradle.daemon=false' >> $HOME/.gradle/gradle.properties
      - name: Build and publish release
        id: build
        run: ./gradlew -PdistributionRepository=$(pwd)/deployment-repository build publishAllPublicationsToDeploymentRepository
      - name: Stage
        uses: spring-io/artifactory-deploy-action@aba148f1541e09adcf5735af90029fac9a6d3083 # v0.0.5
        with:
          uri: 'https://repo.spring.io'
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          build-name: ${{ format('develocity-conventions-{0}', needs.get-version.outputs.version)}}
          repository: 'libs-staging-local'
          folder: 'deployment-repository'
          signing-key: ${{ secrets.GPG_PRIVATE_KEY }}
          signing-passphrase: ${{ secrets.GPG_PASSPHRASE }}
  sync-to-maven-central:
    name: Sync to Maven Central
    needs:
      - get-version
      - build-and-stage-release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@deda456d982fc5e9a7a020b63eb0d2968aedd33e # v5.1.0
        env:
          JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      - name: Download release artifacts
        run: jf rt download --spec .github/release-artifacts.spec --spec-vars 'buildName=${{ format('develocity-conventions-{0}', needs.get-version.outputs.version) }};buildNumber=${{ github.run_number }}'
      - name: Sync
        uses: spring-io/central-publish-action@5ea05c77127404d89c374ac4cd17b6ec6b0e7293 # v0.4.0
        with:
          token: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          token-name: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
  promote-release:
    name: Promote release
    needs:
      - build-and-stage-release
      - get-version
      - sync-to-maven-central
    runs-on: ubuntu-latest
    steps:
      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@deda456d982fc5e9a7a020b63eb0d2968aedd33e # v5.1.0
        env:
          JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      - name: Promote build
        run: jfrog rt build-promote ${{ format('develocity-conventions-{0}', needs.get-version.outputs.version)}} ${{ github.run_number }} libs-release-local
  create-github-release:
    name: Create GitHub release
    needs:
      - promote-release
      - get-version
    runs-on: ubuntu-latest
    steps:
      - name: Generate changelog
        uses: spring-io/github-changelog-generator@f7d7a87a3e7c627ecb8c26cf086c38ac5a939721 # 0.0.14
        with:
          milestone: ${{ needs.get-version.outputs.version }}
          token: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} --repo ${{ github.repository }} --notes-file changelog.md
