name: "Validate Gradle Wrapper"
on: [push, pull_request]

jobs:
  validate-gradle-wrapper:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: gradle/wrapper-validation-action@b231772637bb498f11fdbc86052b6e8a8dc9fc92 # v2.1.2
